# Generated by Django 5.2.1 on 2025-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_medicine_created_at_medicine_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, default='medimages/defaultimage.jpg', null=True, upload_to='medimages'),
        ),
    ]
