# Generated by Django 5.2.1 on 2025-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_medicine_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer_profile',
            old_name='shopename',
            new_name='shop_name',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
