# Generated by Django 5.2.1 on 2025-05-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.dealer_profile'),
        ),
    ]
